version: '3.8'

services:

  # PostgreSQL for Hono
  postgres-hono:
    image: postgres:latest
    container_name: postgres-hono
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hono
    ports:
      - "5441:5432"
    volumes:
      - postgres-hono-data:/var/lib/postgresql/data
    networks:
      - better-auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  better-auth-network:
    driver: bridge

volumes:
  postgres-hono-data: